"""Regression tests for bugs found during a deliberate review/polish
pass (2026-06-20), testing deliberately messy real-world-shaped input
(garbage, empty files, binary files) rather than only the clean
fixtures generated by synthetic_fixtures.py.

Every test here corresponds to a real bug that was found and fixed,
not a hypothetical edge case -- each one originally produced a raw
Python stack trace instead of a clean error message.
"""

from pathlib import Path

from typer.testing import CliRunner

from tollgate.cli import app
from tollgate.validation.models import RuleId
from tollgate.validation.xsd_validator import validate_xsd

SCHEMA_PATH = (
    Path(__file__).parent.parent
    / "src"
    / "tollgate"
    / "schemas"
    / "pacs.008.001.08.xsd"
)

runner = CliRunner()


def test_completely_non_xml_input_does_not_crash():
    """BUG 1: validate_xsd() previously let xmlschema's
    XMLResourceParseError propagate uncaught for input that isn't
    valid XML at all (as opposed to XML that's merely
    schema-nonconformant). A user pointing the tool at the wrong file
    got a raw stack trace.
    """
    violations = validate_xsd("this is not xml at all", SCHEMA_PATH)
    assert len(violations) == 1
    assert violations[0].rule_id == RuleId.XSD_STRUCTURAL
    assert "could not be parsed as xml" in violations[0].message.lower()


def test_plain_string_without_angle_bracket_does_not_leak_internal_paths():
    """BUG FOUND testing the README quickstart example directly: a
    plain string with no '<' character (e.g. "not even xml") made
    xmlschema's resource loader treat it as a potential file PATH,
    raising an exception whose text echoed back a local filesystem
    path ("can't access to resource 'file:///home/...'"). The fix
    stopped surfacing the raw exception text at all -- this test
    guards specifically against a local path fragment leaking into
    the user-facing message again.
    """
    violations = validate_xsd("not even xml", SCHEMA_PATH)
    assert len(violations) == 1
    message_lower = violations[0].message.lower()
    assert "file://" not in message_lower
    assert "/home/" not in message_lower
    assert "errno" not in message_lower
    assert "no such file or directory" not in message_lower


def test_empty_string_input_does_not_resolve_to_cwd():
    """BUG 2: an empty string, once encoded to b"", was apparently
    treated by xmlschema as 'no source provided' rather than 'empty
    document' -- it fell back to resolving the current working
    directory as a file:// URL, raising a confusing 'Is a directory'
    OSError that told the user nothing about their actual problem.
    """
    violations = validate_xsd("", SCHEMA_PATH)
    assert len(violations) == 1
    assert "empty" in violations[0].message.lower()
    assert "directory" not in violations[0].message.lower()


def test_empty_file_does_not_resolve_to_cwd(tmp_path):
    """Same bug as above, via the Path-based code path rather than
    the raw-string code path -- both need the same guard.
    """
    empty_file = tmp_path / "empty.xml"
    empty_file.touch()

    violations = validate_xsd(empty_file, SCHEMA_PATH)
    assert len(violations) == 1
    assert "empty" in violations[0].message.lower()


def test_cli_handles_non_xml_file_cleanly(tmp_path):
    """End-to-end: the CLI itself should never show a raw traceback
    for malformed input, regardless of which layer would otherwise
    raise.
    """
    bad_file = tmp_path / "garbage.xml"
    bad_file.write_text("this is not xml at all", encoding="utf-8")

    result = runner.invoke(app, ["validate", str(bad_file)])
    assert result.exit_code == 1
    assert "Traceback" not in result.stdout
    assert "xsd_structural" in result.stdout


def test_cli_handles_empty_file_cleanly(tmp_path):
    empty_file = tmp_path / "empty.xml"
    empty_file.touch()

    result = runner.invoke(app, ["validate", str(empty_file)])
    assert result.exit_code == 1
    assert "Traceback" not in result.stdout
    normalized = " ".join(result.stdout.lower().split())
    assert "empty" in normalized


def test_cli_handles_binary_file_cleanly(tmp_path):
    """BUG 3: Path.read_text(encoding="utf-8") in the CLI raised an
    uncaught UnicodeDecodeError for binary input (e.g. someone
    accidentally pointing the tool at a non-text file).
    """
    binary_file = tmp_path / "binary.xml"
    binary_file.write_bytes(b"\x00\x01\x02\xff\xfe\x80\x81")

    result = runner.invoke(app, ["validate", str(binary_file)])
    assert result.exit_code == 1
    assert "Traceback" not in result.stdout
    normalized = " ".join(result.stdout.lower().split())
    assert "utf-8" in normalized or "binary" in normalized


def test_cli_handles_directory_path_cleanly(tmp_path):
    """Passing a directory instead of a file should fail clearly,
    not attempt to read it as a file and crash.
    """
    result = runner.invoke(app, ["validate", str(tmp_path)])
    assert result.exit_code == 1
    assert "Traceback" not in result.stdout
    normalized = " ".join(result.stdout.lower().split())
    assert "directory" in normalized


def test_unrelated_valid_xml_does_not_crash():
    """A well-formed XML document that simply isn't ISO 20022 at all
    (e.g. an RSS feed) should fail with a clean schema-mismatch error,
    not crash -- this already worked correctly, included here as a
    regression guard alongside the other malformed-input cases found
    in the same review pass.
    """
    rss_xml = """<?xml version="1.0"?>
<rss version="2.0"><channel><title>Test</title></channel></rss>"""

    violations = validate_xsd(rss_xml, SCHEMA_PATH)
    assert len(violations) >= 1
    assert violations[0].rule_id == RuleId.XSD_STRUCTURAL


def test_multi_transaction_message_violations_are_still_caught():
    """Known limitation (documented in docs/SOURCES.md#known-
    limitations): field_path doesn't disambiguate which transaction a
    violation is in for multi-transaction messages, but the violation
    itself must still be found regardless of which transaction it's in.
    """
    from lxml import etree

    from tollgate.generator.synthetic_fixtures import build_valid_baseline, inject_error
    from tollgate.validation.charset_rule import check_charset

    xml1 = build_valid_baseline(seed=1)
    baseline2 = build_valid_baseline(seed=2)
    xml2, _ = inject_error(baseline2, RuleId.CHARSET_VIOLATION)

    root1 = etree.fromstring(xml1.encode("utf-8"))
    root2 = etree.fromstring(xml2.encode("utf-8"))
    ns = {"p": root1.nsmap.get(None)}

    tx2 = root2.find(".//p:CdtTrfTxInf", ns)
    fi_to_fi = root1.find(".//p:FIToFICstmrCdtTrf", ns)
    fi_to_fi.append(tx2)

    multi_tx_xml = etree.tostring(
        root1, xml_declaration=True, encoding="UTF-8", pretty_print=True
    ).decode("utf-8")

    violations = check_charset(multi_tx_xml)
    assert len(violations) >= 1, (
        "A violation in the second of two transactions must still be "
        "found, even though field_path doesn't disambiguate which "
        "transaction it came from."
    )
